// Linux TurboModule header generator.
//
// Takes a NativeModuleSchema (from `@react-native/codegen`'s parser)
// and emits a self-contained C++ header that:
//
//   • Declares an abstract `<SpecName>Spec` extending
//     `rnlinux::TurboModule` (which is `facebook::jsi::HostObject`).
//   • One pure virtual per method, with C++ types mapped from the
//     spec via `mapType`.
//   • Inline overrides of `get(rt, name)` and `getPropertyNames(rt)`
//     that dispatch every spec method to the virtuals via
//     `facebook::jsi::Function::createFromHostFunction`.
//
// The implementer subclasses the spec and overrides one virtual per
// method — no JSI plumbing in user code. See
// vnext/src/modules/PlatformConstants.cpp for a worked example.

import {mapType, type TypeAnnotation} from './types';

interface MethodShape {
  name: string;
  optional: boolean;
  typeAnnotation: {
    type: 'FunctionTypeAnnotation';
    params: Array<{name: string; typeAnnotation: TypeAnnotation; optional?: boolean}>;
    returnTypeAnnotation: TypeAnnotation;
  };
}

interface NativeModuleSchema {
  type: 'NativeModule';
  moduleName: string;
  spec: {methods: MethodShape[]};
}

// Top-level container for one spec file. The CLI/script entry point
// hands one of these into `generateModule` per parsed module.
export interface SpecModule {
  // The TypeScript module name — strips the leading `Native` (e.g.
  // `NativePlatformConstantsLinux`). Drives the output filename
  // (`<specName>Spec.h`) and the C++ class name.
  specName: string;
  // The runtime module name as it appears in
  // `TurboModuleRegistry.get('Foo')` — distinct from specName.
  moduleName: string;
  schema: NativeModuleSchema;
}

export interface GenerateOptions {
  // Filename header banner. Defaults to a generic marker.
  banner?: string;
}

// Render a single spec module as `<specName>Spec.h`. Returns the
// header contents; the caller decides where on disk it goes.
export function generateModule(mod: SpecModule, opts: GenerateOptions = {}): string {
  const {specName, moduleName, schema} = mod;
  const banner =
    opts.banner ??
    `// Auto-generated by @lucid-softworks/react-native-linux-codegen.\n// Source: ${specName}.ts (module: ${moduleName}). DO NOT EDIT.`;

  const methods = schema.spec.methods;
  const className = `${specName}Spec`;

  const lines: string[] = [];
  lines.push(banner);
  lines.push('');
  lines.push('#pragma once');
  lines.push('');
  lines.push('#include <jsi/jsi.h>');
  lines.push('#include <jsi/JSIDynamic.h>');
  lines.push('#include <react-native-linux/RuntimeExecutor.h>');
  lines.push('#include <react-native-linux/TurboModuleRegistry.h>');
  lines.push('#include <folly/dynamic.h>');
  lines.push('');
  lines.push('#include <cstdint>');
  lines.push('#include <functional>');
  lines.push('#include <memory>');
  lines.push('#include <string>');
  lines.push('#include <utility>');
  lines.push('#include <vector>');
  lines.push('');
  lines.push('namespace rnlinux::codegen {');
  lines.push('');
  lines.push(`class ${className} : public rnlinux::TurboModule {`);
  lines.push(' public:');
  lines.push(`  static constexpr const char* kModuleName = "${moduleName}";`);
  lines.push('');
  lines.push('  // Implementer overrides one virtual per spec method.');
  for (const method of methods) {
    lines.push(`  ${renderVirtualSignature(method)} = 0;`);
  }
  lines.push('');
  lines.push('  // JSI dispatch (do not override).');
  lines.push(
    '  facebook::jsi::Value get(facebook::jsi::Runtime& rt, const facebook::jsi::PropNameID& name) override {',
  );
  lines.push('    const auto methodName = name.utf8(rt);');
  for (const method of methods) {
    lines.push(
      ...renderDispatchBranch(method)
        .split('\n')
        .map(l => `    ${l}`),
    );
  }
  lines.push('    return facebook::jsi::Value::undefined();');
  lines.push('  }');
  lines.push('');
  lines.push(
    '  std::vector<facebook::jsi::PropNameID> getPropertyNames(facebook::jsi::Runtime& rt) override {',
  );
  lines.push('    std::vector<facebook::jsi::PropNameID> out;');
  lines.push(`    out.reserve(${methods.length});`);
  for (const method of methods) {
    lines.push(`    out.emplace_back(facebook::jsi::PropNameID::forUtf8(rt, "${method.name}"));`);
  }
  lines.push('    return out;');
  lines.push('  }');
  lines.push('};');
  lines.push('');
  lines.push('} // namespace rnlinux::codegen');
  lines.push('');

  return lines.join('\n');
}

function isPromise(t: TypeAnnotation): boolean {
  return t.type === 'PromiseTypeAnnotation';
}

// Lower a Promise<T> element type to the C++ type accepted by the
// resolve callback. Void promises take a no-arg resolve; everything
// else takes the mapped C++ type of the element.
function promiseResolveType(t: TypeAnnotation): string | null {
  const inner = t.elementType as TypeAnnotation | undefined;
  if (!inner || inner.type === 'VoidTypeAnnotation') return null;
  return mapType(inner, 'return').cpp;
}

function renderVirtualSignature(method: MethodShape): string {
  const params = method.typeAnnotation.params.map((p, i) => {
    const cppType = mapType(p.typeAnnotation, 'param').cpp;
    const argName = p.name || `arg${i}`;
    return `${cppType} ${argName}`;
  });
  const ret = method.typeAnnotation.returnTypeAnnotation;
  if (isPromise(ret)) {
    const resolveCpp = promiseResolveType(ret);
    const resolveSig =
      resolveCpp === null
        ? 'std::function<void()> resolve'
        : `std::function<void(${resolveCpp})> resolve`;
    const rejectSig = 'std::function<void(folly::dynamic)> reject';
    const all = [...params, resolveSig, rejectSig].join(', ');
    return `virtual void ${method.name}(${all})`;
  }
  const retType = mapType(ret, 'return');
  return `virtual ${retType.cpp} ${method.name}(${params.join(', ')})`;
}

interface UnpackedParam {
  // Local variable name as it appears in the unpack line and the
  // executor capture list. Same as the spec param name (or `argN`).
  varName: string;
}

function isCallback(t: TypeAnnotation): boolean {
  return t.type === 'FunctionTypeAnnotation';
}

function renderDispatchBranch(method: MethodShape): string {
  const params = method.typeAnnotation.params;
  const paramCount = params.length;
  const ret = method.typeAnnotation.returnTypeAnnotation;

  // Body lines are rendered at the indent level that matches the
  // surrounding lambda body (8 spaces here; an outer 4 gets added
  // when the branch is composed into the dispatcher).
  const BODY = '        ';
  const unpackLines: string[] = [];
  const unpacked: UnpackedParam[] = [];

  const hasCallback = params.some(p => isCallback(p.typeAnnotation));
  const needsExecutor = hasCallback || isPromise(ret);
  if (needsExecutor) {
    unpackLines.push(`${BODY}auto __executor = rnlinux::getRuntimeExecutor();`);
  }

  params.forEach((p, i) => {
    const argName = p.name || `arg${i}`;
    if (isCallback(p.typeAnnotation)) {
      unpackLines.push(...renderCallbackUnpack(p.typeAnnotation, argName, i, BODY));
    } else {
      const pType = mapType(p.typeAnnotation, 'param');
      const unpack = pType.fromJsi!(`args[${i}]`, 'rt_');
      unpackLines.push(`${BODY}auto ${argName} = ${unpack};`);
    }
    unpacked.push({varName: argName});
  });

  if (isPromise(ret)) {
    return renderPromiseDispatchBranch(method, unpackLines, unpacked, BODY);
  }

  const retType = mapType(ret, 'return');
  const callArgs = unpacked.map(u => `std::move(${u.varName})`).join(', ');
  const callExpr = `this->${method.name}(${callArgs})`;

  let returnExpr: string;
  if (retType.cpp === 'void') {
    unpackLines.push(`${BODY}${callExpr};`);
    returnExpr = 'facebook::jsi::Value::undefined()';
  } else {
    unpackLines.push(`${BODY}auto __result = ${callExpr};`);
    returnExpr = retType.toJsi!('__result', 'rt_');
  }

  return [
    `if (methodName == "${method.name}") {`,
    `  return facebook::jsi::Function::createFromHostFunction(`,
    `      rt,`,
    `      facebook::jsi::PropNameID::forUtf8(rt, "${method.name}"),`,
    `      /*paramCount=*/${paramCount},`,
    `      [this](facebook::jsi::Runtime& rt_, const facebook::jsi::Value& /*thisVal*/,`,
    `             const facebook::jsi::Value* ${paramCount > 0 ? 'args' : '/*args*/'},`,
    `             size_t /*count*/) -> facebook::jsi::Value {`,
    ...unpackLines,
    `${BODY}return ${returnExpr};`,
    `      });`,
    `}`,
  ].join('\n');
}

// Unpack a callback (Function-typed) param as a std::function. The
// jsi::Function is wrapped via shared_ptr (jsi::Function is move-only,
// std::function needs CopyConstructible), and the std::function body
// hops to the JS thread via __executor before calling. C++ args
// supplied by the user are moved into the executor's inner-lambda
// capture and converted to jsi::Value on the JS-thread side.
//
// MVP only supports void-returning callbacks (`(...args) => void`),
// which covers ~every TM spec in the wild (success/error /
// onProgress / onChange patterns). Non-void returns throw earlier
// from `mapType`.
function renderCallbackUnpack(
  t: TypeAnnotation,
  varName: string,
  argIndex: number,
  BODY: string,
): string[] {
  const fn = t as {
    params?: Array<{name?: string; typeAnnotation: TypeAnnotation}>;
  };
  const cbParams = fn.params ?? [];
  const argInfos = cbParams.map((p, i) => {
    const cppType = mapType(p.typeAnnotation, 'param').cpp;
    const name = p.name || `a${i}`;
    const toJsi = mapType(p.typeAnnotation, 'param').toJsi;
    if (!toJsi) {
      throw new Error(
        `Callback arg "${name}" has type ${p.typeAnnotation.type} which has no toJsi mapping — ` +
          'nested callbacks / unsupported types are not yet handled.',
      );
    }
    return {cppType, name, toJsi};
  });

  const fnSig = argInfos.map(a => `${a.cppType} ${a.name}`).join(', ');
  const callArgs = argInfos.map(a => a.toJsi(`__cb_${a.name}`, '__rt')).join(', ');
  const moveCaptures =
    argInfos.length === 0
      ? ''
      : ', ' + argInfos.map(a => `__cb_${a.name} = std::move(${a.name})`).join(', ');
  const outerCaptures =
    argInfos.length === 0 ? `[__fn_${varName}, __executor]` : `[__fn_${varName}, __executor]`;

  const cppType = `std::function<void(${argInfos.map(a => a.cppType).join(', ')})>`;

  // jsi::Function isn't copy-constructible; wrap in shared_ptr so the
  // std::function holding it can be passed by value into the virtual.
  return [
    `${BODY}auto __fn_${varName} = std::make_shared<facebook::jsi::Function>(`,
    `${BODY}    args[${argIndex}].asObject(rt_).asFunction(rt_));`,
    `${BODY}${cppType} ${varName} =`,
    `${BODY}    ${outerCaptures}(${fnSig}) mutable {`,
    `${BODY}      if (!__executor) return;`,
    `${BODY}      __executor([__fn_${varName}${moveCaptures}](facebook::jsi::Runtime& __rt) mutable {`,
    `${BODY}        __fn_${varName}->call(__rt${callArgs ? ', ' + callArgs : ''});`,
    `${BODY}      });`,
    `${BODY}    };`,
  ];
}

// Promise-returning methods: the host function constructs a JS
// Promise via the global Promise constructor and threads
// resolve/reject as std::function callbacks into the virtual. The
// virtual's resolve takes the C++ form of Promise<T>'s element; the
// reject always takes folly::dynamic (jsi-convertible).
//
// Resolve / reject lambdas hop back via the host's RuntimeExecutor
// before touching the runtime, so user code can call them off-thread.
function renderPromiseDispatchBranch(
  method: MethodShape,
  unpackLines: string[],
  unpacked: UnpackedParam[],
  BODY: string,
): string {
  const ret = method.typeAnnotation.returnTypeAnnotation;
  const resolveCpp = promiseResolveType(ret);
  const paramCount = method.typeAnnotation.params.length;

  // Resolve / reject lambdas hop back to the JS thread via the
  // host's RuntimeExecutor before touching the runtime. Captured
  // rt_exec is only valid while the executor lambda is on the
  // stack, so we route every callback through `__executor` (which
  // detects same-thread and invokes synchronously when the user
  // resolves inline). The resolve/reject std::function values can
  // safely be moved off-thread.
  let resolveLambda: string;
  if (resolveCpp === null) {
    resolveLambda =
      'std::function<void()> resolve = [resolveFn, __executor]() { ' +
      'if (!__executor) return; ' +
      '__executor([resolveFn](facebook::jsi::Runtime& __rt) { ' +
      'resolveFn->call(__rt, facebook::jsi::Value::undefined()); ' +
      '}); };';
  } else {
    const elem = (ret.elementType as TypeAnnotation) ?? {type: 'VoidTypeAnnotation'};
    const toJsi = mapType(elem, 'return').toJsi!('__value', '__rt');
    resolveLambda =
      `std::function<void(${resolveCpp})> resolve = ` +
      `[resolveFn, __executor](${resolveCpp} value) mutable { ` +
      `if (!__executor) return; ` +
      `__executor([resolveFn, __value = std::move(value)](facebook::jsi::Runtime& __rt) mutable { ` +
      `resolveFn->call(__rt, ${toJsi}); ` +
      `}); };`;
  }

  const rejectLambda =
    'std::function<void(folly::dynamic)> reject = ' +
    '[rejectFn, __executor](folly::dynamic value) mutable { ' +
    'if (!__executor) return; ' +
    '__executor([rejectFn, __value = std::move(value)](facebook::jsi::Runtime& __rt) mutable { ' +
    'rejectFn->call(__rt, facebook::jsi::valueFromDynamic(__rt, __value)); ' +
    '}); };';

  // Capture-by-move (init-capture) so the executor owns the unpacked
  // args even though the outer host function lambda has already
  // returned by the time the JS engine calls the executor. Also
  // capture __executor by value so the resolve/reject lambdas can
  // hop back to the JS thread later.
  const moveCaptures = unpacked.map(u => `${u.varName} = std::move(${u.varName})`).join(', ');
  const captureList =
    unpacked.length === 0 ? '[self, __executor]' : `[self, __executor, ${moveCaptures}]`;

  const allCallArgs = [
    ...unpacked.map(u => `std::move(${u.varName})`),
    'std::move(resolve)',
    'std::move(reject)',
  ].join(', ');
  const callExpr = `self->${method.name}(${allCallArgs})`;

  return [
    `if (methodName == "${method.name}") {`,
    `  return facebook::jsi::Function::createFromHostFunction(`,
    `      rt,`,
    `      facebook::jsi::PropNameID::forUtf8(rt, "${method.name}"),`,
    `      /*paramCount=*/${paramCount},`,
    `      [this](facebook::jsi::Runtime& rt_, const facebook::jsi::Value& /*thisVal*/,`,
    `             const facebook::jsi::Value* ${paramCount > 0 ? 'args' : '/*args*/'},`,
    `             size_t /*count*/) -> facebook::jsi::Value {`,
    ...unpackLines,
    `${BODY}auto Promise = rt_.global().getPropertyAsFunction(rt_, "Promise");`,
    `${BODY}auto self = this;`,
    // `__executor` is already in scope — the dispatch-branch builder
    // adds it before the unpack lines whenever this branch needs it.
    `${BODY}auto executor = facebook::jsi::Function::createFromHostFunction(`,
    `${BODY}    rt_,`,
    `${BODY}    facebook::jsi::PropNameID::forUtf8(rt_, "executor"),`,
    `${BODY}    /*paramCount=*/2,`,
    `${BODY}    ${captureList}(`,
    `${BODY}        facebook::jsi::Runtime& rt_exec,`,
    `${BODY}        const facebook::jsi::Value& /*thisVal*/,`,
    `${BODY}        const facebook::jsi::Value* execArgs,`,
    `${BODY}        size_t /*count*/) mutable -> facebook::jsi::Value {`,
    `${BODY}      auto resolveFn = std::make_shared<facebook::jsi::Function>(`,
    `${BODY}          execArgs[0].asObject(rt_exec).asFunction(rt_exec));`,
    `${BODY}      auto rejectFn = std::make_shared<facebook::jsi::Function>(`,
    `${BODY}          execArgs[1].asObject(rt_exec).asFunction(rt_exec));`,
    `${BODY}      ${resolveLambda}`,
    `${BODY}      ${rejectLambda}`,
    `${BODY}      ${callExpr};`,
    `${BODY}      return facebook::jsi::Value::undefined();`,
    `${BODY}    });`,
    `${BODY}return Promise.callAsConstructor(rt_, executor);`,
    `      });`,
    `}`,
  ].join('\n');
}
