// Linux TurboModule header generator.
//
// Takes a NativeModuleSchema (from `@react-native/codegen`'s parser)
// and emits a self-contained C++ header that:
//
//   • Declares an abstract `<SpecName>Spec` extending
//     `rnlinux::TurboModule` (which is `facebook::jsi::HostObject`).
//   • One pure virtual per method, with C++ types mapped from the
//     spec via `mapType`.
//   • Inline overrides of `get(rt, name)` and `getPropertyNames(rt)`
//     that dispatch every spec method to the virtuals via
//     `facebook::jsi::Function::createFromHostFunction`.
//
// The implementer subclasses the spec and overrides one virtual per
// method — no JSI plumbing in user code. See
// vnext/src/modules/PlatformConstants.cpp for a worked example.

import {mapType, type TypeAnnotation} from './types';

interface MethodShape {
  name: string;
  optional: boolean;
  typeAnnotation: {
    type: 'FunctionTypeAnnotation';
    params: Array<{name: string; typeAnnotation: TypeAnnotation; optional?: boolean}>;
    returnTypeAnnotation: TypeAnnotation;
  };
}

interface NativeModuleSchema {
  type: 'NativeModule';
  moduleName: string;
  spec: {methods: MethodShape[]};
}

// Top-level container for one spec file. The CLI/script entry point
// hands one of these into `generateModule` per parsed module.
export interface SpecModule {
  // The TypeScript module name — strips the leading `Native` (e.g.
  // `NativePlatformConstantsLinux`). Drives the output filename
  // (`<specName>Spec.h`) and the C++ class name.
  specName: string;
  // The runtime module name as it appears in
  // `TurboModuleRegistry.get('Foo')` — distinct from specName.
  moduleName: string;
  schema: NativeModuleSchema;
}

export interface GenerateOptions {
  // Filename header banner. Defaults to a generic marker.
  banner?: string;
}

// Render a single spec module as `<specName>Spec.h`. Returns the
// header contents; the caller decides where on disk it goes.
export function generateModule(mod: SpecModule, opts: GenerateOptions = {}): string {
  const {specName, moduleName, schema} = mod;
  const banner =
    opts.banner ??
    `// Auto-generated by @lucid-softworks/react-native-linux-codegen.\n// Source: ${specName}.ts (module: ${moduleName}). DO NOT EDIT.`;

  const methods = schema.spec.methods;
  const className = `${specName}Spec`;

  const lines: string[] = [];
  lines.push(banner);
  lines.push('');
  lines.push('#pragma once');
  lines.push('');
  lines.push('#include <jsi/jsi.h>');
  lines.push('#include <jsi/JSIDynamic.h>');
  lines.push('#include <react-native-linux/TurboModuleRegistry.h>');
  lines.push('#include <folly/dynamic.h>');
  lines.push('');
  lines.push('#include <cstdint>');
  lines.push('#include <string>');
  lines.push('#include <vector>');
  lines.push('');
  lines.push('namespace rnlinux::codegen {');
  lines.push('');
  lines.push(`class ${className} : public rnlinux::TurboModule {`);
  lines.push(' public:');
  lines.push(`  static constexpr const char* kModuleName = "${moduleName}";`);
  lines.push('');
  lines.push('  // Implementer overrides one virtual per spec method.');
  for (const method of methods) {
    lines.push(`  ${renderVirtualSignature(method)} = 0;`);
  }
  lines.push('');
  lines.push('  // JSI dispatch (do not override).');
  lines.push(
    '  facebook::jsi::Value get(facebook::jsi::Runtime& rt, const facebook::jsi::PropNameID& name) override {',
  );
  lines.push('    const auto methodName = name.utf8(rt);');
  for (const method of methods) {
    lines.push(
      ...renderDispatchBranch(method)
        .split('\n')
        .map(l => `    ${l}`),
    );
  }
  lines.push('    return facebook::jsi::Value::undefined();');
  lines.push('  }');
  lines.push('');
  lines.push(
    '  std::vector<facebook::jsi::PropNameID> getPropertyNames(facebook::jsi::Runtime& rt) override {',
  );
  lines.push('    std::vector<facebook::jsi::PropNameID> out;');
  lines.push(`    out.reserve(${methods.length});`);
  for (const method of methods) {
    lines.push(`    out.emplace_back(facebook::jsi::PropNameID::forUtf8(rt, "${method.name}"));`);
  }
  lines.push('    return out;');
  lines.push('  }');
  lines.push('};');
  lines.push('');
  lines.push('} // namespace rnlinux::codegen');
  lines.push('');

  return lines.join('\n');
}

function renderVirtualSignature(method: MethodShape): string {
  const ret = mapType(method.typeAnnotation.returnTypeAnnotation, 'return');
  const params = method.typeAnnotation.params.map((p, i) => {
    const cppType = mapType(p.typeAnnotation, 'param').cpp;
    const argName = p.name || `arg${i}`;
    return `${cppType} ${argName}`;
  });
  return `virtual ${ret.cpp} ${method.name}(${params.join(', ')})`;
}

function renderDispatchBranch(method: MethodShape): string {
  const ret = mapType(method.typeAnnotation.returnTypeAnnotation, 'return');
  const params = method.typeAnnotation.params;
  const paramCount = params.length;

  // Build the body that unpacks args and calls the virtual. Each
  // body line is rendered at the indent level that matches the
  // surrounding lambda body (8 spaces here; an outer 4 gets added
  // when the branch is composed into the dispatcher).
  const BODY = '        ';
  const unpackLines: string[] = [];
  const callArgs: string[] = [];
  params.forEach((p, i) => {
    const argName = p.name || `arg${i}`;
    const pType = mapType(p.typeAnnotation, 'param');
    const unpack = pType.fromJsi!(`args[${i}]`, 'rt_');
    unpackLines.push(`${BODY}auto ${argName} = ${unpack};`);
    callArgs.push(`std::move(${argName})`);
  });

  const callExpr = `this->${method.name}(${callArgs.join(', ')})`;

  let returnExpr: string;
  if (ret.cpp === 'void') {
    unpackLines.push(`${BODY}${callExpr};`);
    returnExpr = 'facebook::jsi::Value::undefined()';
  } else {
    unpackLines.push(`${BODY}auto __result = ${callExpr};`);
    returnExpr = ret.toJsi!('__result', 'rt_');
  }

  return [
    `if (methodName == "${method.name}") {`,
    `  return facebook::jsi::Function::createFromHostFunction(`,
    `      rt,`,
    `      facebook::jsi::PropNameID::forUtf8(rt, "${method.name}"),`,
    `      /*paramCount=*/${paramCount},`,
    `      [this](facebook::jsi::Runtime& rt_, const facebook::jsi::Value& /*thisVal*/,`,
    `             const facebook::jsi::Value* ${paramCount > 0 ? 'args' : '/*args*/'},`,
    `             size_t /*count*/) -> facebook::jsi::Value {`,
    ...unpackLines,
    `${BODY}return ${returnExpr};`,
    `      });`,
    `}`,
  ].join('\n');
}
