import path from 'path';
import fs from 'fs';
import chalk from 'chalk';
import type {Command, Config} from '@react-native-community/cli-types';
import type {LinuxDependencyConfig} from '../platformConfig';

interface AutolinkLinuxOpts {
  outputFile: string;
  check: boolean;
}

interface LinkedDependency {
  name: string;
  sourceDir: string;
  cmakeTarget: string;
}

/**
 * `autolink-linux`
 *
 * Walks `ctx.dependencies` looking for entries whose `platforms.linux` is a
 * non-null `LinuxDependencyConfig`, then emits a CMake include file that
 * pulls each one in via `add_subdirectory` and links it into the host app
 * target.
 *
 * The generated file is consumed by the app's `linux/CMakeLists.txt` like:
 *
 *     include(${CMAKE_CURRENT_SOURCE_DIR}/build/autolinked.cmake OPTIONAL)
 *     ...
 *     target_link_libraries(rn-linux-app PRIVATE ${RN_LINUX_AUTOLINKED_TARGETS})
 *
 * The `--check` flag short-circuits writing and exits non-zero if the
 * existing file is out of date (CI guardrail).
 */
export const autolinkLinux: Command = {
  name: 'autolink-linux',
  description:
    'Generate a CMake include listing the autolinked native dependencies',
  options: [
    {
      name: '--output-file <path>',
      description: 'Where to write the generated CMake include',
      default: 'linux/build/autolinked.cmake',
    },
    {
      name: '--check',
      description: 'Exit non-zero if the output file is out of date',
      default: false,
    },
  ],
  func: async (_argv: string[], ctx: Config, opts: AutolinkLinuxOpts) => {
    const linked = collectLinkedDependencies(ctx);
    const generated = renderCmake(linked);
    const outPath = path.resolve(ctx.root, opts.outputFile);

    if (opts.check) {
      const existing = fs.existsSync(outPath)
        ? fs.readFileSync(outPath, 'utf8')
        : '';
      if (existing.trim() !== generated.trim()) {
        console.error(
          chalk.red(
            `✗ ${path.relative(ctx.root, outPath)} is out of date. ` +
              'Re-run `react-native autolink-linux`.',
          ),
        );
        process.exitCode = 1;
        return;
      }
      console.log(chalk.green(`✓ ${path.relative(ctx.root, outPath)} is up to date`));
      return;
    }

    fs.mkdirSync(path.dirname(outPath), {recursive: true});
    fs.writeFileSync(outPath, generated);
    console.log(
      chalk.green(
        `✓ Wrote ${path.relative(ctx.root, outPath)} ` +
          `(${linked.length} linked native module${linked.length === 1 ? '' : 's'})`,
      ),
    );
  },
};

export function collectLinkedDependencies(ctx: Config): LinkedDependency[] {
  const out: LinkedDependency[] = [];
  const deps = (ctx.dependencies ?? {}) as Record<
    string,
    {root: string; platforms?: {linux?: LinuxDependencyConfig | null}}
  >;
  for (const name of Object.keys(deps).sort()) {
    const dep = deps[name];
    const linux = dep.platforms?.linux;
    if (!linux) continue;
    if (!linux.cmakeTarget) {
      console.warn(
        chalk.yellow(
          `! ${name} declares a linux platform but no cmakeTarget — skipping.`,
        ),
      );
      continue;
    }
    out.push({
      name,
      sourceDir: linux.sourceDir,
      cmakeTarget: linux.cmakeTarget,
    });
  }
  return out;
}

export function renderCmake(linked: LinkedDependency[]): string {
  const lines: string[] = [];
  lines.push('# Auto-generated by @lucid-softworks/react-native-linux-cli');
  lines.push('# Re-run `react-native autolink-linux` after adding or removing');
  lines.push('# native dependencies. Do not edit by hand.');
  lines.push('');
  lines.push('set(RN_LINUX_AUTOLINKED_TARGETS "")');
  for (const dep of linked) {
    const cleaned = dep.name.replace(/[^a-zA-Z0-9_]/g, '_');
    lines.push('');
    lines.push(`# ${dep.name}`);
    lines.push(`add_subdirectory("${dep.sourceDir}" rn_linux_dep_${cleaned})`);
    lines.push(
      `list(APPEND RN_LINUX_AUTOLINKED_TARGETS ${dep.cmakeTarget})`,
    );
  }
  lines.push('');
  return lines.join('\n');
}
