import {collectLinkedDependencies, renderCmake} from '../commands/autolinkLinux';

describe('collectLinkedDependencies', () => {
  test('returns an empty list when ctx has no dependencies', () => {
    const ctx = {root: '/r', dependencies: {}} as any;
    expect(collectLinkedDependencies(ctx)).toEqual([]);
  });

  test('skips deps that opted out (platforms.linux === null)', () => {
    const ctx = {
      root: '/r',
      dependencies: {
        foo: {root: '/r/node_modules/foo', platforms: {linux: null}},
        bar: {root: '/r/node_modules/bar', platforms: {}},
      },
    } as any;
    expect(collectLinkedDependencies(ctx)).toEqual([]);
  });

  test('skips deps that declare linux without a cmakeTarget, warning', () => {
    const warn = jest.spyOn(console, 'warn').mockImplementation(() => {});
    const ctx = {
      root: '/r',
      dependencies: {
        broken: {
          root: '/r/node_modules/broken',
          platforms: {linux: {sourceDir: '/r/node_modules/broken/linux'}},
        },
      },
    } as any;
    expect(collectLinkedDependencies(ctx)).toEqual([]);
    expect(warn).toHaveBeenCalledTimes(1);
    warn.mockRestore();
  });

  test('returns linked deps sorted by package name', () => {
    const ctx = {
      root: '/r',
      dependencies: {
        'z-pkg': {
          root: '/r/node_modules/z-pkg',
          platforms: {
            linux: {
              sourceDir: '/r/node_modules/z-pkg/linux',
              cmakeTarget: 'z_pkg',
            },
          },
        },
        'a-pkg': {
          root: '/r/node_modules/a-pkg',
          platforms: {
            linux: {
              sourceDir: '/r/node_modules/a-pkg/linux',
              cmakeTarget: 'a_pkg',
            },
          },
        },
      },
    } as any;
    const linked = collectLinkedDependencies(ctx);
    expect(linked.map(d => d.name)).toEqual(['a-pkg', 'z-pkg']);
  });
});

describe('renderCmake', () => {
  test('emits the empty header when no deps are linked', () => {
    const out = renderCmake([]);
    expect(out).toContain('Auto-generated by @lucid-softworks/react-native-linux-cli');
    expect(out).toContain('set(RN_LINUX_AUTOLINKED_TARGETS "")');
    expect(out).not.toContain('add_subdirectory');
  });

  test('emits add_subdirectory + list APPEND for each dep', () => {
    const out = renderCmake([
      {
        name: '@scope/lib',
        sourceDir: '/abs/path/to/lib/linux',
        cmakeTarget: 'scope_lib',
      },
    ]);
    expect(out).toContain('# @scope/lib');
    expect(out).toContain('add_subdirectory("/abs/path/to/lib/linux" rn_linux_dep__scope_lib)');
    expect(out).toContain('list(APPEND RN_LINUX_AUTOLINKED_TARGETS scope_lib)');
  });

  test('sanitizes invalid CMake identifier chars from package name', () => {
    const out = renderCmake([
      {
        name: '@foo/bar-baz.qux',
        sourceDir: '/x',
        cmakeTarget: 't',
      },
    ]);
    // hyphens and dots and @ and / are all replaced with underscores
    expect(out).toContain('rn_linux_dep__foo_bar_baz_qux');
  });
});
