#!/usr/bin/env node
'use strict';

/**
 * react-native-linux codegen driver.
 *
 * Walks the JS package (and the playground app, if `--include-app` is
 * passed) for `*NativeComponent.{ts,tsx,js}` and `Native*.{ts,tsx,js}`
 * spec files, then drives `@react-native/codegen` to emit C++ headers
 * under `--output`.
 *
 * IMPORTANT (2026-05-22): `@react-native/codegen` only ships first-class
 * generators for `android` and `ios`. Until we fork the codegen package
 * (mirroring react-native-windows's `@react-native-windows/codegen`) or
 * upstream a `linux` platform, this driver:
 *
 *   1. Resolves all spec files in the package.
 *   2. Writes a manifest (`.codegen-stamp.json`) listing them.
 *   3. Returns success — the manifest is what CMake's
 *      add_custom_command stamps on so downstream builds know "we have
 *      run the codegen step against this set of inputs".
 *
 * The actual `.h` emission lands once the linux generator exists. Until
 * then, vnext/src/ uses the same upstream `react/renderer/components/
 * view/*Props.h` etc. that RN already publishes for View and Paragraph.
 *
 * Exit codes:
 *    0  ok
 *    1  arg parsing
 *    2  package directory missing
 *    3  no specs found (warning, not failure)
 */

const fs = require('node:fs');
const path = require('node:path');

function parseArgs(argv) {
  const args = {package: null, output: null, includeApp: false};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--package') args.package = argv[++i];
    else if (a === '--output') args.output = argv[++i];
    else if (a === '--include-app') args.includeApp = true;
    else if (a === '-h' || a === '--help') {
      process.stdout.write(`Usage: codegen/run.js --package DIR --output DIR [--include-app]\n`);
      process.exit(0);
    }
  }
  return args;
}

function walkSpecs(rootDir) {
  /** @type {string[]} */
  const hits = [];
  if (!fs.existsSync(rootDir)) return hits;

  const stack = [rootDir];
  while (stack.length) {
    const dir = stack.pop();
    let entries;
    try {
      entries = fs.readdirSync(dir, {withFileTypes: true});
    } catch {
      continue;
    }
    for (const entry of entries) {
      if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
      } else if (entry.isFile()) {
        if (/(NativeComponent|Native[A-Z][^.]*)\.(ts|tsx|js)$/.test(entry.name)) {
          hits.push(full);
        }
      }
    }
  }
  return hits.sort();
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.package || !args.output) {
    console.error('Missing --package or --output. See --help.');
    process.exit(1);
  }
  if (!fs.existsSync(args.package)) {
    console.error(`Package directory not found: ${args.package}`);
    process.exit(2);
  }

  const specs = walkSpecs(args.package);
  if (specs.length === 0) {
    console.warn(`[codegen] no specs found under ${args.package}; emitting empty stamp.`);
  } else {
    console.log(`[codegen] discovered ${specs.length} spec file(s):`);
    for (const s of specs) {
      console.log(`  - ${path.relative(process.cwd(), s)}`);
    }
  }

  fs.mkdirSync(args.output, {recursive: true});
  const manifest = {
    generatedAt: new Date().toISOString(),
    package: path.resolve(args.package),
    specs: specs.map((s) => path.relative(args.package, s)),
    notice:
      'Manifest only — the linux platform generator for @react-native/codegen ' +
      'is not yet implemented. See TODO.md Phase 5.6 and the comment at the ' +
      'top of scripts/codegen/run.js.',
  };
  fs.writeFileSync(
    path.join(args.output, '.codegen-stamp.json'),
    JSON.stringify(manifest, null, 2) + '\n',
  );

  // Emit a placeholder header so consumers that #include
  // "react-native-linux/codegen/Markers.h" don't fail when codegen
  // hasn't run with real content yet.
  const markerHeader = [
    '// Auto-generated by scripts/codegen/run.js. Do not edit.',
    '#pragma once',
    '',
    'namespace rnlinux::codegen {',
    `inline constexpr unsigned int kSpecCount = ${specs.length}u;`,
    '}  // namespace rnlinux::codegen',
    '',
  ].join('\n');
  fs.writeFileSync(path.join(args.output, 'Markers.h'), markerHeader);
}

main();
